version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=teachio
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_DB=teachio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
