version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=teachio
      - POSTGRES_PASSWORD=s3cret
      - POSTGRES_DB=teachio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9-management-alpine
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=teachio
      - RABBITMQ_DEFAULT_PASS=teachio
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles: ["rabbitmq"]

  redis:
    image: redis:6
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
