version: '3'

services:
  postgres:
    restart: always
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_PASSWORD=s3cret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
