# Generated by Django 3.2.10 on 2021-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
