# Generated by Django 3.1.7 on 2021-11-20 22:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('status', models.CharField(choices=[('NotConfirmed', 'NotConfirmed'), ('Requested', 'Requested'), ('Confirmed', 'Confirmed')], default='NotConfirmed', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
