# Generated by Django 3.2.9 on 2021-12-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
