name: ci

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    name: Build and push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/kekasquad/teachio:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896

      - name: Notify if failed
        if: ${{ failure() }}
        env:
          NOTIFY_URL: ${{ secrets.NOTIFY_URL }}
        run: curl -X POST ${NOTIFY_URL} --data-urlencode 'message=$GITHUB_REPOSITORY build and push failed' --data-urlencode 'disable_notification=true'

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: ${{ secrets.SSH_CONFIG }}
          if_key_exists: fail
      - name: Pull and restart on server
        run: |
          ssh deploy-host-01 'cd nginx/apps/teachio-backend && ./deploy.sh'

      - name: Notify success
        env:
          NOTIFY_URL: ${{ secrets.NOTIFY_URL }}
        run: curl -X POST ${NOTIFY_URL} --data-urlencode "message=$GITHUB_REPOSITORY deployed successfully" --data-urlencode 'disable_notification=true'

      - name: Notify if failed
        if: ${{ failure() }}
        env:
          NOTIFY_URL: ${{ secrets.NOTIFY_URL }}
        run: curl -X POST ${NOTIFY_URL} --data-urlencode "message=$GITHUB_REPOSITORY deploy failed, more info https://github.com/$GITHUB_REPOSITORY/runs/$GITHUB_ACTION" --data-urlencode 'disable_notification=true'
